config/routes.rb
Test3::Application.routes.draw do
  resources :chapters

  resources :pages do
member do 
post 'push'
end

end

  resources :users

  resources :books
  resources :compares

  resources :lines do
    member do
       post 'sign' 
    end
  end

   root :to => "users#index"

end

app/models/line.rb
class Line < ActiveRecord::Base


  acts_as_list :column => "pos", :scope => :parent

  default_scope order('pos ASC') #lazy!
belongs_to :page
#default_scope :order => 'microposts.created_at DESC'
#  acts_as_list :column => "pos"


end

app/controllers/lines_controller.rb
class LinesController < ApplicationController

  before_filter :find_page , :only => [ :index, :new]
#response_with :html
  def index
@lines = @page.lines.find(:all, :conditions => "parent_id = #{@page.id}", :order => 'pos')
  end

  def show
    @line = Line.find(params[:id])
  end
  


  def new
  @line = @page.lines.build

#(:parent_id =>)
@line.parent_id = @page.id
@line.pos = @page.lines.length
  #(:parent_id => 20 , :pos =>  params[:pos].to_i + 1 )
  end

  def sign

line = Line.find(params[:id])
pos = line.pos 
#parent = line.parent_id
@page  = Page.find(line.page_id)

  @line = @page.lines.new(:parent_id => line.page_id , :pos => pos , :content => "+")
@line.save
#render :controller => 'page' , :action => 'show' , :page_id => parent.to_s

#show_page_path(:page_id => parent.to_s)

redirect_to page_path :id => @page.id
#lines_url , :page_id => parent.to_s
  end

  def create
    @line = Line.new(params[:line])

@line.content = '?' if @line.content.empty?
    if @line.save
      redirect_to @line, :notice => "Successfully created line."
    else
      render :action => 'new'
    end
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    if @line.update_attributes(params[:line])
      redirect_to @line, :notice  => "Successfully updated line."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    @line.destroy
    redirect_to lines_url, :notice => "Successfully destroyed line."
  end
private 
def find_page
@page = Page.find(params[:page_id])
end
end
 # def new1
 # @line = Line.new(:parent_id => 20 , :pos =>  params[:pos].to_i + 1 )
 # end

app/helpers/lines_helper.rb
module LinesHelper
  def show_magic lines
    arr = []
lines.each do |line|
arr <<  line.content
end
str = arr.join('=')
  end
end

app/views/lines/_form.html.erb
<%= form_for @line do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.label :page_id %><br />
    <%= f.text_field :page_id %>
  </p>
  <p>
    <%= f.label :parent_id %><br />
    <%= f.text_field :parent_id %>
  </p>
  <p>
    <%= f.label :pos %><br />
    <%= f.text_field :pos %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/lines/_line.html.erb
<%= link_to @line.content, @line %>
<%= link_to "Reply", new_line_path(:parent_id => @line) %> |

app/views/lines/edit.html.erb
<% title "Edit Line" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @line %> |
  <%= link_to "View All", lines_path %>
</p>

app/views/lines/index.html.erb
<% title "Lines" %>

<table>
  <tr>
    <th>Content</th>
    <th>Page</th>
    <th>Parent</th>
    <th>Pos</th>
  </tr>
  <% for line in @lines %>
    <tr>
      <td><%= line.content %></td>
      <td><%= line.page_id %></td>
      <td><%= line.parent_id %></td>
      <td><%= line.pos %></td>
      <td><%= link_to "Show", line %></td>
      <td><%= link_to "Edit", edit_line_path(line) %></td>
      <td><%= link_to "Destroy", line, :confirm => 'Are you sure?', :method => :delete %></td>
 
      <td><%= link_to "PUSH", sign_line_path( :id => line.id), :method => :post , :class => 'button' %></td>


    </tr>
  <% end %>
</table>
<%= show_magic @lines %>
<p><%= link_to "New Line", new_line_path(:page_id => @page.id) %></p>

app/views/lines/new.html.erb
<% title "New Line" %>

<%= render 'form' %>

<p><%= link_to "Back to List", lines_path %></p>

app/views/lines/show.html.erb
<% title "Line" %>

<p>
  <strong>Content:</strong>
  <%= @line.content %>
</p>
<p>
  <strong>Page:</strong>
  <%= @line.page_id %>
</p>
<p>
  <strong>Parent:</strong>
  <%= @line.parent_id %>
</p>
<p>
  <strong>Pos:</strong>
  <%= @line.pos %>
</p>

<p>
  <%= link_to "Edit", edit_line_path(@line) %> |
  <%= link_to "Destroy", @line, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", lines_path(:page_id => @line.page_id) %>

</p>