config/routes.rb
Test3::Application.routes.draw do
  resources :chapters

  resources :pages do
member do 
post 'push'
end

end

  resources :users

  resources :books
  resources :compares

  resources :lines do
    member do
       post 'sign' 
    end
  end

   root :to => "users#index"

end

app/views/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </p>
  <p>
    <%= f.label :compare_id %><br />
    <%= f.text_field :compare_id %>
  </p>
  <p>
    <%= f.label :lang_id %><br />
    <%= f.text_field :lang_id %>
  </p>
  <p>
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/pages/_page.html.erb
<p>
  <% if @readers && @readers[0] && @readers[1] && @readers[0].length > 0 && @readers[1].length > 0  %>
    <table>
      <% @min.times do |i|  %>

        <tr>

          <% @readers.each do |reader| %>
            <%  line = reader[i] %>
            <td><%= link_to "#{line.pos}) #{line.content}" , push_page_path(:id => line.page_id , :line_id => line.id), :method => :post  %></td>
          <% end %>


        </tr>
      <% end %>
    </table>
  <% end %>
</p>

app/views/pages/edit.html.erb
<% title "Edit Page" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @page %> |
  <%= link_to "View All", pages_path %>
</p>

app/views/pages/index.html.erb
<% title "Pages" %>

<%= render 'pages/page' if @pages %>
<table>
  <tr>
    <th>Number</th>
    <th>Compare_id</th>
    <th>Lang</th>
    <th>Lines Content</th>
  </tr>
  <% for page in @pages %>
    <tr>
      <td><%= page.number %></td>
      <td><%= page.compare_id %></td>
      <td><%= page.lang_id %></td>
      <td><%= show_magic(page.lines) %></td>
      <td><%= link_to "Show", page %></td>
      <td><%= link_to "Edit", edit_page_path(page) %></td>
      <td><%= link_to "Destroy", page, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>




<p><%= link_to "New Page", new_page_path(:compare_id => @compare.id) %></p>

app/views/pages/new.html.erb
<% title "New Page" %>

<%= render 'form' %>

<p><%= link_to "Back to List", pages_path %></p>

app/views/pages/push.js.erb
$("#pages").html("<%= escape_javascript(render(@pages)) %>");

app/views/pages/show.html.erb
<% title "Page" %>

<p>
  <strong>Number:</strong>
  <%= @page.number %>
</p>
<p>
  <strong>Compare:</strong>
  <%= @page.compare_id %>
</p>
<p>
  <strong>Lang:</strong>
  <%= @page.lang_id %>
</p>

<p>


  <strong>Lines:</strong>
   <%= render :template => 'lines/index' %>

</p>
<p>
  <%= link_to "Edit", edit_page_path(@page) %> |
  <%= link_to "Destroy", @page, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", pages_path(:compare_id => @page.compare_id)%>
</p>