config/routes.rb
Test3::Application.routes.draw do
  resources :chapters

  resources :pages do
member do 
post 'push'
end

end

  resources :users

  resources :books
  resources :compares

  resources :lines do
    member do
       post 'sign' 
    end
  end

   root :to => "users#index"

end

app/models/compare.rb
class Compare < ActiveRecord::Base
has_many :pages
belongs_to :chapter


  def feed
    # This is preliminary. See Chapter 12 for the full implementation.
    Page.where("page_id = ?", id)
  end
end

app/controllers/compares_controller.rb
class ComparesController < ApplicationController

  before_filter :find_chapter , :only => [:index, :new]
  # GET /compares
  # GET /compares.xml
  def index
    @compares = @chapter.compares

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @compares }
    end
  end

  # GET /compares/1
  # GET /compares/1.xml
  def show
    @compare = Compare.find(params[:id])
@pages = @compare.pages

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @compare }
    end
  end

  # GET /compares/new
  # GET /compares/new.xml
  def new
    @compare = @chapter.compares.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @compare }
    end
  end

  # GET /compares/1/edit
  def edit
    @compare = Compare.find(params[:id])
  end

  # POST /compares
  # POST /compares.xml
  def create
    @compare = Compare.new(params[:compare])

    respond_to do |format|
      if @compare.save
        format.html { redirect_to(@compare, :notice => 'Compare was successfully created.') }
        format.xml  { render :xml => @compare, :status => :created, :location => @compare }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @compare.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /compares/1
  # PUT /compares/1.xml
  def update
    @compare = Compare.find(params[:id])

    respond_to do |format|
      if @compare.update_attributes(params[:compare])
        format.html { redirect_to(@compare, :notice => 'Compare was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @compare.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /compares/1
  # DELETE /compares/1.xml
  def destroy
    @compare = Compare.find(params[:id])
    @compare.destroy

    respond_to do |format|
      format.html { redirect_to(compares_url) }
      format.xml  { head :ok }
    end
  end
def find_chapter
@chapter = Chapter.find(params[:chapter_id])
end

end

app/helpers/compares_helper.rb
module ComparesHelper
end

app/views/compares/_form.html.erb
<%= form_for(@compare) do |f| %>
  <% if @compare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compare.errors.count, "error") %> prohibited this compare from being saved:</h2>

      <ul>
      <% @compare.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chapter_id %><br />
    <%= f.text_field :chapter_id %>
  </div>
  <div class="field">
    <%= f.label :page_number_relative %><br />
    <%= f.text_field :page_number_relative %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/compares/edit.html.erb
<h1>Editing compare</h1>

<%= render 'form' %>

<%= link_to 'Show', @compare %> |
<%= link_to 'Back', compares_path %>

app/views/compares/index.html.erb
<h1>Listing compares</h1>

<table>
  <tr>
    <th>Chapter</th>
    <th>Page number relative</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @compares.each do |compare| %>
  <tr>
    <td><%= compare.chapter_id %></td>
    <td><%= compare.page_number_relative %></td>
    <td><%= link_to 'Show', compare %></td>
    <td><%= link_to 'Edit', edit_compare_path(compare) %></td>
    <td><%= link_to 'Destroy', compare, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />


<p><%= link_to "New Compare", new_compare_path(:chapter_id => @chapter.id) %></p>

app/views/compares/new.html.erb
<h1>New compare</h1>

<%= render 'form' %>

<%= link_to 'Back', compares_path %>

app/views/compares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Chapter:</b>
  <%= @compare.chapter_id %>
</p>

<p>
  <b>Page number relative:</b>
  <%= @compare.page_number_relative %>
</p>

  <strong>Pages:</strong>
   <%= render :template => 'pages/index' %>


<%= link_to 'Edit', edit_compare_path(@compare) %> |
<%= link_to 'Back', compares_path(:chapter_id => @compare.chapter_id) %>